# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: pipeline-self
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Instala o Node.js
- task: UseNode@1
  inputs:
    version: '16.x'

# Instalar dependências do Node.js
- script: npm install
  displayName: 'Install Node.js dependencies'
  
- task: Docker@2
  inputs:
    containerRegistry: 'acrdemoapijefferson'
    repository: 'api-dio-test'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'